### ISSUE TITLE
dashboard not working after I logout the server

### ISSUE THREAD

**Issue by Garykings** [Ticketmaster/metrilyx-2.0#100]
Hi Guys,

Recently I installed Metrilyx 2.5.1. The thing is that it works fine when I started Metrilyx and when I logout, it stopped working. there are lots of errors in  the datalog as 
[ERROR metrilyx.dataserver.transforms 367] 
Any suggestion?

Regards,
Gary

**Comment by euforia** [comment]
Did you install using the rpm or pip?

**Comment by Garykings** [comment]
Hi euforia,

I installed using rpm.

**Comment by euforia** [comment]
apologies for the delayed response. would you mind trying to install it using this link - https://github.com/Ticketmaster/metrilyx-2.0/blob/master/docs/Installation.md

I have a suspicion the rpm has not been assembled correctly.  Unfortunately I haven't had a chance to get around to it.  Let me know how that works out.  I may just give you a docker image instead :)

**Comment by euforia** [comment]
You can also refer to this issue - https://github.com/Ticketmaster/metrilyx-2.0/issues/90

Closing for now feel free to open.
