### ISSUE TITLE
Data modeling

### ISSUE THREAD

**Issue by sinamorawej** [Ticketmaster/metrilyx-2.0#101]
Hi 
Maybe this question has been asked before (in which case I apologize in advance) but is there a way of setting up graphs in metrilyx to display data points without any statistical distortions? 
Why the question? we have a tsd forwarder counting number of unique sessions per minute in apache logs and forwarding that data to tsd. I can generate graphs which correspond to real data in tsd ui (for example N sessions at 10:01:45 however in metrilyx this is proving rather hard to achieve (lambda functions could hold the answer but I'm not too sure what needs to be applied to data points).

thanks,
~sina

**Comment by euforia** [comment]
The problem your facing is on the rendering side.  Highcharts (the graphing library) groups data points if the number of data points is greater than the width of the graph.  If you zoom in to the graph or if the chart width is larger than than data point count, the data will not get distorted.  

Let me know if that doesn't make sense.  I can try to explain further.

cheers,

**Comment by sinamorawej** [comment]
Thanks - it kind of makes sense. So, based on what we are seeing which is distorted minute by minute data in a 1hr window am I correct in assuming if our collection/forwarding times was to increase from say 1 to 2 mins we will get actual values?

**Comment by euforia** [comment]
Yes assuming your chart is wide enough to hold all the data you would see exact values.

**Comment by sinamorawej** [comment]
is there a way to auto scale width in order for it to display correct values?

**Comment by euforia** [comment]
No autoscaling at the moment,  Just a size change.

**Comment by euforia** [comment]
Closing. Feel free to open if necessary.
