### ISSUE TITLE
metrilyx-modelmanager cannot start successfully

### ISSUE THREAD

**Issue by liutaihua** [Ticketmaster/metrilyx-2.0#102]
#/etc/init.d/metrilyx-modelmanager start
metrilyx-modelmanager starting... [failed]

#cat log/metrilyx-modelmanager.log 
/etc/init.d/metrilyx-modelmanager: 39: /etc/init.d/metrilyx-modelmanager: --ini: not found

and there it not found quickstart document at repo

and i run django server with manager.py:
python manager.py runserver :8080 
but got 404 page http://localhost:8080/
i can't find any entry of website, help!

Ubuntu 14.04.3 LTS  python 2.7.6  django 1.6(as the requirement)

**Comment by euforia** [comment]
Looks like uwsgi is not nstalled.  Refer to this issue which has more details

https://github.com/Ticketmaster/metrilyx-2.0/issues/103

I'll leave this open until I hear back.

**Comment by euforia** [comment]
I've added a patch to handle this situation.  Please retry.
