### ISSUE TITLE
metrilyx-modelmanager init issue 

### ISSUE THREAD

**Issue by sadoyan** [Ticketmaster/metrilyx-2.0#103]
Hi  There is problem with metrilyx-modelmanager. 

Init script does not start model-manager. 
most likely reason is that is cannot find modelmanager ${BIN}. 

after exporting all vars in init script I got this: 
echo ${PYTHONPATH} ${PYTHON_EGG_CACHE} ${APP_HOME} ${BIN} ${DEFAULT_OPTS}  ${LOGFILE}

/opt/metrilyx/usr/lib/python2.6/site-packages:/opt/metrilyx/usr/lib64/python2.6/site-packages /dev/shm/metrilyx /opt/metrilyx --ini /opt/metrilyx/etc/metrilyx/uwsgi.conf --uid www-data --gid www-data /opt/metrilyx/log/metrilyx-modelmanager.log

I'm not sure if binary i missing as well however this is content of /opt/metrilyx/bin 

cfgmgr.py  mdlmgr.py  metrilyx-cacher.darwin.amd64  metrilyx-cacher.linux.amd64  metrilyx-dataserver.py  set-run-env.sh

I have installed metrilyx using recommended method on Ubuntu 14.04.3 LTS 64 Bit

**Comment by sadoyan** [comment]
ok seems I have figured it out. 

during installation it does not  compiles uwsgi binary those APP_HOME/usr was empty. 

I have manually compiled uwsgi and put it inside $APP_HOME/usr. 

after that metrilyx-modelmanager started.

**Comment by euforia** [comment]
Glad it worked.  I'll note that in the docs.
