### ISSUE TITLE
Unexpcted operator

### ISSUE THREAD

**Issue by PChiberre** [Ticketmaster/metrilyx-2.0#106]
Hello,
I am trying to run metrilyx but I get unexpected operator for every command and nothing seems to be running.

here is the result of the command 

./metrilyx: 18: [: /usr/local/bin/uwsgi: unexpected operator
/etc/init.d/metrilyx-cacher: 18: [: /usr/local/bin/uwsgi: unexpected operator
metrilyx-cacher running... 10156
/etc/init.d/metrilyx-dataserver: 18: [: /usr/local/bin/uwsgi: unexpected operator
metrilyx-dataserver running... 10179 10199 10219
/etc/init.d/metrilyx-modelmanager: 18: [: /usr/local/bin/uwsgi: unexpected operator
metrilyx-modelmanager running... 10246 10250 10251 10252 10253 10254 10255 10256 10257 10258 10259 10260 10261 10262 10263 10264 10265 10266 10267 10268 10269

when I tried
 cat /usr/local/bin/uwsgi

I got an unreadable output here is a few lines:
F��J�F��r��J0F8�r��HJ0�r�@J0F�rȏIhJ��E�r�I�J��E �r؏I�J0F0�r�H�J��E �r����E(�r�I���E(�r�J�F��r.�I@J�F��r9�IpJpF��rG�IpJpF��rT�I�J�F��ri�I�J�F��r��H}�I0Fp�r��IJ�Fx�r��I@J��Eh�r_�O��I0�D��IxJ`�DŐIѐI@�D��I�JpF��rC�I��I��E@�r�I�I�FD�r7�I�I�FD�rBJIPJpEE7JI�JpEEJI0JpEE"JI�JpEE[�IJ�Ft�r(JI@JpGE{�Ip�I-F�oIp�I-F��IxJ-F��IxJ-F��I�J0F`�r��I�J0F`�r��I��I�F<�rՑI��I�F�IJ��EX�r!�IHJ��EX�r0�IxJ�F(�r=�I�J�F,�rI�I�JPFc�I\�I�Fi�I0J�FonIp�Ip�E��IXJ�xF��I�J0yF��I�J�yF��IPJpF��I��I�F.�HH!JH�McIcI��F �F��F`r`�F�

thanks for your help

**Comment by PChiberre** [comment]
here is also the log from metrilyx-dataserver-9003.log 

2015-12-10 11:13:41,372 [WARNING metrilyx.dataserver.cli 27] * Initializing server...
2015-12-10 11:13:41,372 [WARNING metrilyx.dataserver.cli 33] * Memory threshold: 1500.00 MBs
2015-12-10 11:13:41,372 [WARNING metrilyx.dataserver.cli 73] Starting websocket server: ws://philippe-VirtualBox:9003 [permessage-deflate]

and   metrilyx-modelmanager.log

machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
setgid() to 33
setuid() to 33
your processes number limit is 22125
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /opt/metrilyx/run/modelmanager.sock fd 3
Python version: 2.7.6 (default, Jun 22 2015, 18:01:27)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1367a20
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1527792 bytes (1491 KB) for 20 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1367a20 pid: 10652 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 10652)
spawned uWSGI worker 1 (pid: 10656, cores: 1)
spawned uWSGI worker 2 (pid: 10657, cores: 1)
spawned uWSGI worker 3 (pid: 10658, cores: 1)
spawned uWSGI worker 4 (pid: 10659, cores: 1)
spawned uWSGI worker 5 (pid: 10660, cores: 1)
spawned uWSGI worker 6 (pid: 10661, cores: 1)
spawned uWSGI worker 7 (pid: 10662, cores: 1)
spawned uWSGI worker 8 (pid: 10663, cores: 1)
spawned uWSGI worker 9 (pid: 10664, cores: 1)
spawned uWSGI worker 10 (pid: 10665, cores: 1)
spawned uWSGI worker 11 (pid: 10666, cores: 1)
spawned uWSGI worker 12 (pid: 10667, cores: 1)
spawned uWSGI worker 13 (pid: 10668, cores: 1)
spawned uWSGI worker 14 (pid: 10669, cores: 1)
spawned uWSGI worker 15 (pid: 10670, cores: 1)
spawned uWSGI worker 16 (pid: 10671, cores: 1)
spawned uWSGI worker 17 (pid: 10672, cores: 1)
spawned uWSGI worker 18 (pid: 10673, cores: 1)
spawned uWSGI worker 19 (pid: 10674, cores: 1)
spawned uWSGI worker 20 (pid: 10675, cores: 1)

**Comment by euforia** [comment]
uwsgi is a binary which is why you are seeing what you are when you cat is. Seems like the issue is the parameters passed to uwsgi.  Can you check the metrilyx-modelmanager log as well as the nginx error log?  That should give me more info as to which params it doesn't like

You will also need a resolvable hostname or use the ip address for the websocket.

**Comment by PChiberre** [comment]
the error log from nginx are totally blanc the metrilyx-modelmanager.log is the one I sent on the first message. 

my ip instead of the localhost?

I am running Ubuntu 14.04.3 LTS inside a virtual machine from mac Yosemite 10.10.5 

thanks for your help

**Comment by euforia** [comment]
I think i may have found a bug.  Can you make sure that this https://github.com/Ticketmaster/metrilyx-2.0/blob/master/etc/init.d/metrilyx-modelmanager#L17 particular line matches the one in your installation.    Let me know.

**Comment by PChiberre** [comment]
sorry for the late answer the line does not match, I have : 
BIN=$UWSGI_BIN
thank you

**Comment by euforia** [comment]
Can you change it to match that file and try again?

**Comment by PChiberre** [comment]
It didn't change the error I still had the unexpected operator error

**Comment by euforia** [comment]
Finally figured it out.  Try re-installing from the master branch.  It should be fixed.  There was an error in the startup script when checking for uwsgi.  I've installed on a fresh ubuntu 14.04 box and it checks out.  Closing for now.  Feel free to re-open if the problem persists.

**Comment by PChiberre** [comment]
thanks I'll try it tomorow

**Comment by PChiberre** [comment]
How can I make a fresh install? is there a way to remove everything and reinstall? I have try to upgrade but when running the command
 METRILYX_HOME=$(pwd) ./bin/mdlmgr.py 
I get django.db.utils.OperationalError: no such table: metrilyx_mapmodel

**Comment by euforia** [comment]
you can use `pip uninstall metrilyx-2.0`.  make sure you backup anything needed in  `/opt/metrilyx` first then make sure this directory is removed before you re-install.  

I would highly recommend using docker to play around with the install.

**Comment by PChiberre** [comment]
thanks issue is fixed
