### ISSUE TITLE
New Installation - Graph/data not loading

### ISSUE THREAD

**Issue by pbedadham** [Ticketmaster/metrilyx-2.0#65]
Hi

I did a fresh install on ubuntu(14.04), no issues except cc1plus problem. Able to start metrilyx without any issue.

root@ubuntu:~# /etc/init.d/metrilyx status
metrilyx-cacher running... 4071
metrilyx-dataserver running... 4088 4092
metrilyx-modelmanager running... 4104 4108 4109 4110 4111 4112 4113 4114 4115 4116 4117 4118 4119 4120 4121 4122 4123 4124 4125 4126 4127

Having issue in Graph/data loading, not loading any data and not seeing any errors in the /opt/metrilyx/ logs . I am able to see TSDB metrics in the search(DB connection good!) but graph/data not loading when it is configured in the dashboard(page).

Please help where I can see the log and any configuration missing

**Comment by euforia** [comment]
Was the cc1plus issue resolved?  If not that could be the issue.

Set the log to INFO in the startup script.  This line - https://github.com/Ticketmaster/metrilyx-2.0/blob/master/etc/init.d/metrilyx-dataserver#L13  needs to be changed INFO in /etc/init.d/metrilyx-dataserver.

Then restart the service.  Don't bother putting it to debug as it generates a lot of useless errors from twisted.

Also open the javascript console and let me know if you see anything there.

I'm assuming your /opt/metrilyx/logs/* look clean?

**Comment by bahatelos** [comment]
Hello!

I seem to be experiencing a similar problem on Centos 6 (and ubuntu 14.04), with TSDB data present and available but no graphs being generated in Metrilyx.

A similar cc1plus issue was experienced when trying to install metrilyx via pip
(pip install git+https://github.com/Ticketmaster/metrilyx-2.0.git).

Not a big deal as installing g++ seemed to do the trick.

No errors in any of the logs but there are some javascript errors.

I am attaching a screenshot of the jscript errors and a screenshot of the UI.
![metrilyx_js_errors copy](https://cloud.githubusercontent.com/assets/10450980/5682580/ed28e86a-9818-11e4-96d3-f83303baa7ae.jpg)
![metrilyx_ui_no_graph](https://cloud.githubusercontent.com/assets/10450980/5682581/ed4bfaa8-9818-11e4-98d4-a4939258cb67.jpg)



My pip freeze:

pip freeze
autobahn==0.9.4.post2
cas==0.15
cffi==0.8.6
cryptography==0.7.1
Django==1.6.5
django-cors-headers==0.12
django-filter==0.7
django-reversion==1.8.0
djangorestframework==2.3.13
elasticsearch==1.2.0
enum34==1.0.4
ethtool==0.6
freeipa==2.0.0a0
iniparse==0.3.1
iotop==0.3.2
ipapython==3.0.0
iwlib==1.0
jsonfield==0.9.20
kerberos==1.0
lxml==2.2.3
matplotlib==0.99.1.1
metrilyx==2.4.0
netaddr==0.7.5
nose==0.10.4
numpy==1.9.1
ordereddict==1.1
pandas==0.15.2
paramiko==1.7.5
pyasn1==0.1.7
pycparser==2.10
pycrypto==2.0.1
pycurl==7.19.0
pygpgme==0.1
pymssql==1.0.2
pyOpenSSL==0.14
python-dateutil==1.4.1
python-default-encoding==0.1
python-ldap==2.3.10
python-nss==0.13
pytz==2014.10
requests==2.2.1
six==1.9.0
SSSDConfig==1.9.2
Twisted==13.1.0
ujson==1.33
urlgrabber==3.9.1
urllib3==1.10
uuid==1.30
uWSGI==2.0.9
wsaccel==0.6.2
yum-metadata-parser==1.1.2
zope.interface==4.1.2

**Comment by euforia** [comment]
Thank you.  This is really helpful.  I'll investigate the g++ issue but shouldn't be that bad of a fix.

Did you use the bootstrap script in the docs or just pip directly?

The websocket connection seems to be failing.  Is the hostname for this host resolvable?  I suspect the websocket domain check is what is causing the connection failure.  

Can you send me the output of the following command - 

curl http://<you_host_here>/api/config

This may be a potential bug.

**Comment by euforia** [comment]
The quick start doc is missing g++ for debian based installs.  Docs are updated.

**Comment by bahatelos** [comment]
Hello,

It's a great pleasure to say it all works fine now!
The problem was indeed the resolvable FQDN.
I added an entry to my local /etc/hosts so that the browser can resolve the server's hostname correctly and the graphs now come up as expected!

Thank you very much for your help!

**Comment by euforia** [comment]
Glad its working for now.  Appreciate the feedback.  

I've also pushed up a patch to support ip addresses and up'd the version (2.4.2).  

This version also has support for ubuntu 12 as well and has been added to the testing cycle.

@pbedadham - I'm assuming this will resolve your issue as well.

Updating to 2.4.2 if you're still on 2.4.1 should be as simple as - pip install git+https://.....metrilyx.git

I'm closing this issue out.  Please feel free to re-open if necessary.

**Comment by RowZay** [comment]
I'm also having this same problem. I'm running Ubuntu 14.04 and I followed the current Quick Start guide.

**Comment by euforia** [comment]
This issue has been resolved assuming you have an fqdn or setting the appropriate config option.  If it is still failing, please open a new issue.
