### ISSUE TITLE
Metrilyx CANNOT display opentsdb metrics graph

### ISSUE THREAD

**Issue by fightfate** [Ticketmaster/metrilyx-2.0#66]
Hi,all
We had just established Metrilyx and try to query opentsdb while our opentsdb data are collected with tcollector. We are trying to monitor the cluster diskio situations using tcollector iostat.py

We can catch the TSD module and get the actual io related metrics in Opentsdb. However, cannot say any data grapah normally display in the dashboard. 

Anyone can share their comments about this?

**Comment by euforia** [comment]
Would you be able to provide me with the following info:

- What operating system and distro/version are you using?
- Which method did you use to install? (bootstrap.sh script or pip install from the quickstart guide)
- The output of the following logs under /opt/metrilyx/log/
- Any errors if seen in the javascript console.

The above should give me more insight.

**Comment by euforia** [comment]
Feel free to open it up again if the problem still exists.

**Comment by hugo021** [comment]
i ran into the same problem,how did you reslove it?
