### ISSUE TITLE
Is TSDB 2.1.0RC1 compatible with metrilyx==2.4.3?

### ISSUE THREAD

**Issue by kebarcla** [Ticketmaster/metrilyx-2.0#70]
Hello,

We're able bring up the Metrilyx interface and can log in the Admin page, and we see our metrics listed in the search window. But we never actually see anything get plotted, if we drop a metric onto a panel.

Same for the Overview and TSD panels: I can see labels for things like Memory, but there's just a blue 'busy' widget animating there, with never any graphs.

It looks like we're talking to TSDB OK since we see our metrics listed.

Our setup: Centos 6.4
uname -a
Linux prdslsldsafht50 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

I installed by downloading Anaconda python from https://store.continuum.io/cshop/anaconda and using:

pip install git+https://github.com/Ticketmaster/metrilyx-2.0.git

and everything installed cleanly.

I couldn't get nginx to 'yum install' so I compiled it from source.

Any tips how we can debug why we're not seeing data?

Thanks much
Ken

**Comment by kebarcla** [comment]
Got everything working. Had a conflict with port 80, among other configuration problems.

Really beautiful graphs!

**Comment by euforia** [comment]
I've tested it with the aforementioned release and it seems to work, though the interface will not reflect.  I'm in the process of adding support for it.
