### ISSUE TITLE
web ui error

### ISSUE THREAD

**Issue by louzhenyu** [Ticketmaster/metrilyx-2.0#71]
Hi all,
        I followed the user guide to set up metrilyx, and then access the website, then get these errors:

angular.js:7997 GET http://192.168.5.126/api/graphmaps 502 (Bad Gateway)
angular.js:7997 GET http://192.168.5.126/api/config 502 (Bad Gateway)
angular.js:7997 GET http://192.168.5.126/api/event_types 502 (Bad Gateway)
angular.js:7997 GET http://192.168.5.126/api/schemas/graph 502 (Bad Gateway)
services.js:65 <html>
<head><title>502 Bad Gateway</title></head>

**Comment by euforia** [comment]
Have you checked the server logs /opt/metrilyx/logs/* ?  That should be able to vie me more info.

**Comment by louzhenyu** [comment]
Dear Euforia,
       Msg in metrilyx-cacher.log:
parse :0?max=16000000&q=2&type=metrics: missing protocol scheme
parse :0?max=16000000&q=3&type=metrics: missing protocol scheme
parse :0?max=16000000&q=4&type=metrics: missing protocol scheme
parse :0?max=16000000&q=5&type=metrics: missing protocol scheme
parse :0?max=16000000&q=6&type=metrics: missing protocol scheme
parse :0?max=16000000&q=7&type=metrics: missing protocol scheme
        Msg in metrilyx-dataserver.log:
  from twisted.internet.interfaces import (
/usr/lib/python2.6/site-packages/pytz/__init__.py:29: UserWarning: Module twisted was already imported from /usr/lib64/python2.6/site-packages/twisted/__init__.pyc, but /usr/lib/python2.6/site-packages is being added to sys.path
m twisted.internet.interfaces import (
/usr/lib/python2.6/site-packages/pytz/__init__.py:29: UserWarning: Module twisted was already imported from /usr/lib64/python2.6/site-packages/twisted/__init__.pyc, but /usr/lib/python2.6/site-packages is being added to sys.path
  from pkg_resources import resource_stream
/usr/lib/python2.6/site-packages/pytz/__init__.py:29: UserWarning: Module uuid was already imported from /usr/lib64/python2.6/uuid.pyc, but /usr/lib/python2.6/site-packages is being added to sys.path
  from pkg_resources import resource_stream
2015-03-20 00:14:34,474 [WARNING __main__ 108] Using auto-spawn count.
2015-03-20 00:14:34,475 [WARNING __main__ 115] Performance dataprovider [loaded]
2015-03-20 00:14:34,475 [WARNING __main__ 134] Protocol: <class '__main__.GraphProtocol'>
2015-03-20 00:14:34,475 [WARNING __main__ 136] Spawning 1 server/s...
2015-03-20 00:14:34,479 [WARNING __main__ 64] Started server - ws://localhost:9000

  from pkg_resources import resource_stream
      Msg in  metrilyx-modelmanager.log:
      [uWSGI] getting INI configuration from /opt/metrilyx/etc/metrilyx/uwsgi.conf
*** Starting uWSGI 2.0.4 (64bit) on [Fri Mar 20 00:12:40 2015] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-11) on 19 March 2015 00:45:15
os: Linux-2.6.32-504.el6.x86_64 #1 SMP Wed Oct 15 04:27:16 UTC 2014
nodename: master
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /
detected binary path: /usr/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
setgid() to 498
setuid() to 497
your processes number limit is 7733
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /opt/metrilyx/run/modelmanager.sock fd 3
Python version: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]

I use 2.4.2version for metrilyx. my linux is centos6.6. Could you please give me some advice on what to do?

**Comment by euforia** [comment]
you'll definitely need python 2.6 at least.  looks like a configuration issue as well.

you can also grab the rpm and install it that route - https://github.com/Ticketmaster/metrilyx-2.0/releases

**Comment by louzhenyu** [comment]
[root@master etc]# python
Python 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.

**Comment by louzhenyu** [comment]
Below is the error log from nginx's error log:
2015/03/20 17:48:52 [crit] 3534#0: *3 connect() to unix:///opt/metrilyx/run/modelmanager.sock failed (13: Permission denied) while connecting to upstream, client: 192.168.5.243, server: , request: "GET /api/graphmaps HTTP/1.1", upstream: "uwsgi://unix:///opt/metrilyx/run/modelmanager.sock:", host: "192.168.5.126", referrer: "http://192.168.5.126/"
2015/03/20 17:48:52 [crit] 3534#0: *3 connect() to unix:///opt/metrilyx/run/modelmanager.sock failed (13: Permission denied) while connecting to upstream, client: 192.168.5.243, server: , request: "GET /api/config HTTP/1.1", upstream: "uwsgi://unix:///opt/metrilyx/run/modelmanager.sock:", host: "192.168.5.126", referrer: "http://192.168.5.126/"
2015/03/20 17:48:52 [crit] 3534#0: *5 connect() to unix:///opt/metrilyx/run/modelmanager.sock failed (13: Permission denied) while connecting to upstream, client: 192.168.5.243, server: , request: "GET /api/event_types HTTP/1.1", upstream: "uwsgi://unix:///opt/metrilyx/run/modelmanager.sock:", host: "192.168.5.126", referrer: "http://192.168.5.126/"
2015/03/20 17:48:52 [crit] 3534#0: *4 connect() to unix:///opt/metrilyx/run/modelmanager.sock failed (13: Permission denied) while connecting to upstream, client: 192.168.5.243, server: , request: "GET /api/schemas/graph HTTP/1.1", upstream: "uwsgi://unix:///opt/metrilyx/run/modelmanager.sock:", host: "192.168.5.126", referrer: "http://192.168.5.126/"
2015/03/20 17:48:52 [crit] 3534#0: *1 connect() to unix:///opt/metrilyx/run/modelmanager.sock failed (13: Permission denied) while connecting to upstream, client: 192.168.5.243, server: , request: "GET /api/config HTTP/1.1", upstream: "uwsgi://unix:///opt/metrilyx/run/modelmanager.sock:", host: "192.168.5.126", referrer: "http://192.168.5.126/"
2015/03/20 17:48:57 [error] 3534#0: *1 open() "/opt/metrilyx/www/sys" failed (2: No such file or directory), client: 192.168.5.243, server: , request: "GET /sys HTTP/1.1", host: "192.168.5.126", referrer: "http://192.168.5.126/"

**Comment by louzhenyu** [comment]
change sock chmod to 777 in file:uwsgi.conf,there no error msg in nginx log,but still get 
angular.js:7997 GET http://192.168.5.126/api/graphmaps 502 (Bad Gateway)
angular.js:7997 GET http://192.168.5.126/api/config 502 (Bad Gateway)
angular.js:7997 GET http://192.168.5.126/api/event_types 502 (Bad Gateway)
angular.js:7997 GET http://192.168.5.126/api/schemas/graph 502 (Bad Gateway)
on web browser.

**Comment by euforia** [comment]
What method did you use to install? Some of these errors refers to files not even being part of metrilyx.

**Comment by louzhenyu** [comment]
I just follow quick start, 
execute below commands:
curl -s http://metrilyx.github.io/bootstrap.sh  | bash -s -- install v2.4.2
pip install git+https://github.com/Ticketmaster/metrilyx-2.0.git@v2.4.2
and then change content of /opt/metrilyx/etc/metrilyx/metrilyx.conf

**Comment by euforia** [comment]
Ah, my bad - I've forgotten to update the docs.  Go ahead and grab the rpm for 2.5.0 - https://github.com/Ticketmaster/metrilyx-2.0/releases/download/v2.5.0/metrilyx-2.0-2.5.0-10.el6.x86_64.rpm  

That should work as expected.  In the meantime I'll update the docs as well.  

Let me know how that works out.  I'll keep this issue open till then.

**Comment by louzhenyu** [comment]
Dear Euforia,
         Thank you very much. I'll try if it works.

**Comment by louzhenyu** [comment]
Could you please give me a command list to follow? like quick start.
i met this error when use rpm:
        error: Failed dependencies:
                 python-importlib is needed by metrilyx-2.0-2.5.0-10.el6.x86_64

**Comment by euforia** [comment]
It's only a 1 line command:

yum -y install https://github.com/Ticketmaster/metrilyx-2.0/releases/download/v2.5.0/metrilyx-2.0-2.5.0-10.el6.x86_64.rpm

That error is saying that you're missing required packages.  

i.e yum -y install python-importlib

Do the same for any other packages it complains about.  

Packages not part of the standard distro can be found on the EPEL repository or via the rpmforge repo.

**Comment by louzhenyu** [comment]
After I installed python-importlib, and installing metrilyx still failed with error python-importlib is needed by metrilyx-2.0-2.5.0-10.el6.x86_64

**Comment by louzhenyu** [comment]
it's difficult to use the rpm to install, it's better to list all prerequisite including name and version.

**Comment by louzhenyu** [comment]
follow quickstart and can not start quickly, :(

**Comment by euforia** [comment]
I'm not sure why you're having issues installing the RPM.  I've just installed the same rpm above on a completely new vanilla box without issues.  The box does contain the rpmforge and epel repos. I've attached the commands and output below.  

I have a feeling you do not have the EPEL and RPMFORGE repos installed on your box.

If you would still like todo a manual install then you cannot follow the quickstart guide.  You'll need to follow the installation guide, but these missing dependencies will still be an issue.

============ RUN ============
bash-4.1# cat /etc/redhat-release
CentOS release 6.6 (Final)

bash-4.1# yum -y install https://github.com/Ticketmaster/metrilyx-2.0/releases/download/v2.5.0/metrilyx-2.0-2.5.0-10.el6.x86_64.rpm
Loaded plugins: fastestmirror
Setting up Install Process
metrilyx-2.0-2.5.0-10.el6.x86_64.rpm                                                                     |  29 MB     00:19
Examining /var/tmp/yum-root-kREEEQ/metrilyx-2.0-2.5.0-10.el6.x86_64.rpm: metrilyx-2.0-2.5.0-10.el6.x86_64
Marking /var/tmp/yum-root-kREEEQ/metrilyx-2.0-2.5.0-10.el6.x86_64.rpm to be installed
Loading mirror speeds from cached hostfile
 * base: mirror.keystealth.org
 * epel: dl.fedoraproject.org
 * extras: ftpmirror.your.org
 * rpmforge: mirror.hmc.edu
 * updates: mirrors.kernel.org
Resolving Dependencies
--> Running transaction check
---> Package metrilyx-2.0.x86_64 0:2.5.0-10.el6 will be installed
--> Processing Dependency: atlas for package: metrilyx-2.0-2.5.0-10.el6.x86_64
--> Processing Dependency: blas for package: metrilyx-2.0-2.5.0-10.el6.x86_64
--> Processing Dependency: nginx for package: metrilyx-2.0-2.5.0-10.el6.x86_64
--> Processing Dependency: python-importlib for package: metrilyx-2.0-2.5.0-10.el6.x86_64
--> Processing Dependency: uuid for package: metrilyx-2.0-2.5.0-10.el6.x86_64
--> Processing Dependency: libatlas.so.3()(64bit) for package: metrilyx-2.0-2.5.0-10.el6.x86_64
--> Processing Dependency: liblapack.so.3()(64bit) for package: metrilyx-2.0-2.5.0-10.el6.x86_64
--> Processing Dependency: libptcblas.so.3()(64bit) for package: metrilyx-2.0-2.5.0-10.el6.x86_64
--> Processing Dependency: libptf77blas.so.3()(64bit) for package: metrilyx-2.0-2.5.0-10.el6.x86_64
--> Running transaction check
---> Package atlas.x86_64 0:3.8.4-2.el6 will be installed
---> Package blas.x86_64 0:3.2.1-4.el6 will be installed
---> Package nginx.x86_64 0:1.0.15-11.el6 will be installed
--> Processing Dependency: nginx-filesystem = 1.0.15-11.el6 for package: nginx-1.0.15-11.el6.x86_64
--> Processing Dependency: nginx-filesystem for package: nginx-1.0.15-11.el6.x86_64
--> Processing Dependency: libxslt.so.1(LIBXML2_1.0.18)(64bit) for package: nginx-1.0.15-11.el6.x86_64
--> Processing Dependency: libxslt.so.1(LIBXML2_1.0.11)(64bit) for package: nginx-1.0.15-11.el6.x86_64
--> Processing Dependency: gd for package: nginx-1.0.15-11.el6.x86_64
--> Processing Dependency: GeoIP for package: nginx-1.0.15-11.el6.x86_64
--> Processing Dependency: libxslt.so.1()(64bit) for package: nginx-1.0.15-11.el6.x86_64
--> Processing Dependency: libgd.so.2()(64bit) for package: nginx-1.0.15-11.el6.x86_64
--> Processing Dependency: libexslt.so.0()(64bit) for package: nginx-1.0.15-11.el6.x86_64
--> Processing Dependency: libGeoIP.so.1()(64bit) for package: nginx-1.0.15-11.el6.x86_64
---> Package python-importlib.noarch 0:1.0.2-1.el6.rf will be installed
---> Package uuid.x86_64 0:1.6.1-10.el6 will be installed
--> Running transaction check
---> Package GeoIP.x86_64 0:1.5.1-5.el6 will be installed
---> Package gd.x86_64 0:2.0.35-11.el6 will be installed
--> Processing Dependency: libXpm.so.4()(64bit) for package: gd-2.0.35-11.el6.x86_64
---> Package libxslt.x86_64 0:1.1.26-2.el6_3.1 will be installed
---> Package nginx-filesystem.noarch 0:1.0.15-11.el6 will be installed
--> Running transaction check
---> Package libXpm.x86_64 0:3.5.10-2.el6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================================================================
 Package                     Arch              Version                       Repository                                    Size
================================================================================================================================
Installing:
 metrilyx-2.0                x86_64            2.5.0-10.el6                  /metrilyx-2.0-2.5.0-10.el6.x86_64            134 M
Installing for dependencies:
 GeoIP                       x86_64            1.5.1-5.el6                   epel                                          21 M
 atlas                       x86_64            3.8.4-2.el6                   base                                         2.8 M
 blas                        x86_64            3.2.1-4.el6                   base                                         321 k
 gd                          x86_64            2.0.35-11.el6                 base                                         142 k
 libXpm                      x86_64            3.5.10-2.el6                  base                                          51 k
 libxslt                     x86_64            1.1.26-2.el6_3.1              base                                         452 k
 nginx                       x86_64            1.0.15-11.el6                 epel                                         404 k
 nginx-filesystem            noarch            1.0.15-11.el6                 epel                                         7.9 k
 python-importlib            noarch            1.0.2-1.el6.rf                rpmforge                                     5.6 k
 uuid                        x86_64            1.6.1-10.el6                  base                                          54 k

Transaction Summary
================================================================================================================================
Install      11 Package(s)

Total size: 159 M
Total download size: 25 M
Installed size: 191 M
Downloading Packages:
(1/10): GeoIP-1.5.1-5.el6.x86_64.rpm                                                                     |  21 MB     00:01
(2/10): atlas-3.8.4-2.el6.x86_64.rpm                                                                     | 2.8 MB     00:00
(3/10): blas-3.2.1-4.el6.x86_64.rpm                                                                      | 321 kB     00:00
(4/10): gd-2.0.35-11.el6.x86_64.rpm                                                                      | 142 kB     00:00
(5/10): libXpm-3.5.10-2.el6.x86_64.rpm                                                                   |  51 kB     00:00
(6/10): libxslt-1.1.26-2.el6_3.1.x86_64.rpm                                                              | 452 kB     00:00
(7/10): nginx-1.0.15-11.el6.x86_64.rpm                                                                   | 404 kB     00:00
(8/10): nginx-filesystem-1.0.15-11.el6.noarch.rpm                                                        | 7.9 kB     00:00
(9/10): python-importlib-1.0.2-1.el6.rf.noarch.rpm                                                       | 5.6 kB     00:00
(10/10): uuid-1.6.1-10.el6.x86_64.rpm                                                                    |  54 kB     00:00
--------------------------------------------------------------------------------------------------------------------------------
Total                                                                                            10 MB/s |  25 MB     00:02
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : libxslt-1.1.26-2.el6_3.1.x86_64                                                                             1/11
  Installing : uuid-1.6.1-10.el6.x86_64                                                                                    2/11
  Installing : python-importlib-1.0.2-1.el6.rf.noarch                                                                      3/11
  Installing : atlas-3.8.4-2.el6.x86_64                                                                                    4/11
  Installing : nginx-filesystem-1.0.15-11.el6.noarch                                                                       5/11
  Installing : libXpm-3.5.10-2.el6.x86_64                                                                                  6/11
  Installing : gd-2.0.35-11.el6.x86_64                                                                                     7/11
  Installing : GeoIP-1.5.1-5.el6.x86_64                                                                                    8/11
  Installing : nginx-1.0.15-11.el6.x86_64                                                                                  9/11
  Installing : blas-3.2.1-4.el6.x86_64                                                                                    10/11
  Installing : metrilyx-2.0-2.5.0-10.el6.x86_64                                                                           11/11
  Verifying  : blas-3.2.1-4.el6.x86_64                                                                                     1/11
  Verifying  : GeoIP-1.5.1-5.el6.x86_64                                                                                    2/11
  Verifying  : libXpm-3.5.10-2.el6.x86_64                                                                                  3/11
  Verifying  : nginx-filesystem-1.0.15-11.el6.noarch                                                                       4/11
  Verifying  : atlas-3.8.4-2.el6.x86_64                                                                                    5/11
  Verifying  : python-importlib-1.0.2-1.el6.rf.noarch                                                                      6/11
  Verifying  : nginx-1.0.15-11.el6.x86_64                                                                                  7/11
  Verifying  : uuid-1.6.1-10.el6.x86_64                                                                                    8/11
  Verifying  : metrilyx-2.0-2.5.0-10.el6.x86_64                                                                            9/11
  Verifying  : libxslt-1.1.26-2.el6_3.1.x86_64                                                                            10/11
  Verifying  : gd-2.0.35-11.el6.x86_64                                                                                    11/11

Installed:
  metrilyx-2.0.x86_64 0:2.5.0-10.el6

Dependency Installed:
  GeoIP.x86_64 0:1.5.1-5.el6        atlas.x86_64 0:3.8.4-2.el6                   blas.x86_64 0:3.2.1-4.el6
  gd.x86_64 0:2.0.35-11.el6         libXpm.x86_64 0:3.5.10-2.el6                 libxslt.x86_64 0:1.1.26-2.el6_3.1
  nginx.x86_64 0:1.0.15-11.el6      nginx-filesystem.noarch 0:1.0.15-11.el6      python-importlib.noarch 0:1.0.2-1.el6.rf
  uuid.x86_64 0:1.6.1-10.el6

Complete!

**Comment by louzhenyu** [comment]
Thank you,euforia, You give me enough info to install metrilyx. I'll install  EPEL and RPMFORGE repos first.

**Comment by louzhenyu** [comment]
I've installed successfully, thank u very much!
