### ISSUE TITLE
Support for the `wss://` schema (WebSockets over HTTPS)

### ISSUE THREAD

**Issue by AlexForster** [Ticketmaster/metrilyx-2.0#72]
Using nginx as a frontend for SSL termination, I'm almost able to run Metrilyx over HTTPS. However, there is one issue in [rest/apiviews.py@121](https://github.com/Ticketmaster/metrilyx-2.0/blob/v2.5.1-dev/metrilyx/rest/apiviews.py#L121) where the `ws://` schema is hardcoded.

This is the only issue preventing us from using an unpatched version of Metrilyx. Otherwise, we're loving it!

**Comment by euforia** [comment]
which version are you guys running?

I can definitely make that as a configuration option in metrilyx.conf.  Let me know.

Glad to hear you're using and loving it. :)

**Comment by euforia** [comment]
I've put a patch up with the above change in the v2.5.1-dev branch.  Please take a look and let me know.

- Config change: https://github.com/Ticketmaster/metrilyx-2.0/blob/v2.5.1-dev/etc/metrilyx/metrilyx.conf.sample#L46

- Code change: https://github.com/Ticketmaster/metrilyx-2.0/blob/v2.5.1-dev/metrilyx/rest/apiviews.py#L121

**Comment by AlexForster** [comment]
I've been tracking the changes in 2.5.1-dev and it looks stable enough to me that I've based our deployment on it. Patch looks perfect. Figured it would be about that simple :)

**Comment by euforia** [comment]
2.5.1 - should be released soon anyway and there's not much change aside from performances fixes.

Glad it worked out. :)

**Comment by euforia** [comment]
I'd love see you the ssl changes.  Hopefully get them committed. :)
