### ISSUE TITLE
some error about websocket

### ISSUE THREAD

**Issue by godfreyhe** [Ticketmaster/metrilyx-2.0#73]
dear euforia,

I just setup metrilyx-2.0 on and can see the pages.However when send request http://127.0.0.1:70/index.html#/Overview, I can't see any data, there are some error at Firefox's Console:

GET http://ubuntu/api/data [HTTP/1.1 404 Not Found 0ms]
Firefox can't establish a connection to the server at  ws://ubuntu/api/data?compressed=true. angular-factories.js:496:0
"Disconnected (metrilyx): clean=false, code=1006, reason=''" angular-factories.js:511:0
"iConnect state: disconnected" angular-factories.js:602:20
"Re-connecting..." angular-factories.js:607:24

The request header is:
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:36.0) Gecko/20100101 Firefox/36.0
Upgrade: websocket
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: iJlgDqYDw0jGeRKXycxtgg==
Pragma: no-cache
Origin: http://127.0.0.1:70
Host: ubuntu
Connection: keep-alive, Upgrade
Cache-Control: no-cache
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8

and there is also some error at /opt/metrilyx/log/metrilyx-dataserver.log
2015-03-28 21:47:11,662 [WARNING __main__ 59] Using auto-spawn count: 3
2015-03-28 21:47:11,663 [WARNING __main__ 107] Starting server on: ws://localhost:9000
2015-03-28 21:47:11,663 [WARNING __main__ 107] Starting server on: ws://localhost:9001
2015-03-28 21:47:11,663 [WARNING __main__ 107] Starting server on: ws://localhost:9002
2015-03-28 21:47:11,664 [WARNING __main__ 137] Spawning 3 processes...
2015-03-28 21:47:11,665 [WARNING __main__ 141] Started process (pid 10254): WebSocketServer-1
2015-03-28 21:47:11,665 [WARNING __main__ 51] Memory check (pid 10254) interval: 15 secs
2015-03-28 21:47:11,666 [WARNING __main__ 141] Started process (pid 10255): WebSocketServer-2
2015-03-28 21:47:11,667 [WARNING __main__ 51] Memory check (pid 10255) interval: 15 secs
2015-03-28 21:47:11,667 [WARNING __main__ 141] Started process (pid 10256): WebSocketServer-3
2015-03-28 21:47:11,668 [WARNING __main__ 112] Waiting for memory stats...
2015-03-28 21:47:11,668 [WARNING __main__ 51] Memory check (pid 10256) interval: 15 secs
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/metrilyx/dataserver/spawner.py", line 190, in run
    reactor.run()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 299, in connectionLost
    protocol.connectionLost(reason)
  File "/usr/local/lib/python2.7/dist-packages/autobahn/twisted/websocket.py", line 97, in connectionLost
    self._connectionLost(reason)
  File "/usr/local/lib/python2.7/dist-packages/autobahn/websocket/protocol.py", line 2727, in _connectionLost
    WebSocketProtocol._connectionLost(self, reason)
  File "/usr/local/lib/python2.7/dist-packages/autobahn/websocket/protocol.py", line 1224, in _connectionLost
    self._onClose(self.wasClean, WebSocketProtocol.CLOSE_STATUS_CODE_ABNORMAL_CLOSE, "connection was closed uncleanly (%s)" % self.wasNotCleanReason)
  File "/usr/local/lib/python2.7/dist-packages/autobahn/twisted/websocket.py", line 140, in _onClose
    self.onClose(wasClean, code, reason)
  File "/usr/local/lib/python2.7/dist-packages/metrilyx/dataserver/protocols.py", line 195, in onClose
    self.factory.removeClient(self)
  File "/usr/local/lib/python2.7/dist-packages/metrilyx/dataserver/wsfactory.py", line 16, in removeClient
    self.clients.remove(client)
exceptions.ValueError: list.remove(x): x not in list

I am using:
 "Ubuntu 12.04 LTS",
 Python 2.7.3, 
metrilyx-2.0_2.5.0-12_amd64.deb

the result of socket.gethostname()  is "ubuntu"

the conf /opt/metrilyx/etc/metrilyx/uwsgi.conf : 
#uwsgi.ini file
[uwsgi]
chdir           = /opt/metrilyx
module          = metrilyx.wsgi
master          = true
processes       = 20
#socket          = /opt/metrilyx/run/modelmanager.sock
socket          = /tmp/modelmanager.sock
chmod-socket    = 664
#change to www-data for debian based systems
#uid                            = nginx
uid                             = root
#change to www-data for debian based systems
#gid                            = nginx
gid                             = www-data
vacuum          = true

thank you very much

**Comment by euforia** [comment]
Here's the problem - Firefox can't establish a connection to the server at ws://ubuntu/api/data?compressed=true. angular-factories.js:496:0

The system needs to have a resolvable fqdn, which does not seem to be the case per the logs above.

Let me know if you're still having trouble.

**Comment by godfreyhe** [comment]
I  try to add the 'hostname' field (the value is my pc's ip or 127.0.0.1 ) to the 'websocket' section, but it 's the same error:
Firefox can't establish a connection to the server at ws://IP/api/data?compressed=true

**Comment by euforia** [comment]
Looking through your log - there are several things that may be an issue - you are running a non-standard configuration causing the websocket ports and http ports to not match.  If you choose to do so there are several other places the port value will need to be changed, making troubleshooting quite more difficult.

I would suggest you start by performing a standard install using default values from the quick start section.  Make sure to read through the Configuration section as it details the websocket configuration.

Once you have that working then go back and make your desired changes.

**Comment by godfreyhe** [comment]
I add 'hostname' and 'port' fields to to the 'websocket' section, as
"websocket": {
                "endpoint": "/api/data",
                "hostname": "127.0.0.1",
                "port": 9000
        },

now I can get some graphs:
![screenshot from 2015-03-30 20 05 44](https://cloud.githubusercontent.com/assets/8777671/6895968/a1c39c28-d718-11e4-9432-d8d09a67d648.png)

there are some error at /opt/metrilyx/log/metrilyx-dataserver.log:

2015-03-30 20:03:51,970 [ERROR metrilyx.dataserver.protocols 175] [Failure instance: Traceback: <type 'exceptions.OverflowError'>: Maximum recursion level reached
/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py:578:_runCallbacks
/usr/local/lib/python2.7/dist-packages/metrilyx/httpclients/__init__.py:368:__partialResponseCallback
/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py:383:callback
/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py:491:_startRunCallbacks
--- <exception caught here> ---
/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py:578:_runCallbacks
/usr/local/lib/python2.7/dist-packages/metrilyx/dataserver/protocols.py:169:partialResponseCallback
]
2015-03-30 20:03:51,986 [ERROR metrilyx.dataserver.dataproviders.opentsdb 18] [Failure instance: Traceback: <type 'exceptions.OverflowError'>: Maximum recursion level reached
/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py:578:_runCallbacks
/usr/local/lib/python2.7/dist-packages/metrilyx/httpclients/__init__.py:368:__partialResponseCallback
/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py:383:callback
/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py:491:_startRunCallbacks
--- <exception caught here> ---
/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py:578:_runCallbacks
/usr/local/lib/python2.7/dist-packages/metrilyx/dataserver/protocols.py:169:partialResponseCallback
] - [{u'status': u'querying', u'alias': u'!lambda x: x[\'metric\'].split(\'.\')[-1] + " in MBs"', u'paneIndex': 0, u'yTransform': u'lambda x: x/1024', u'query': {u'aggregator': u'sum', u'metric': u'proc.meminfo.active', u'rate': False, u'tags': {}}}, {u'status': u'querying', u'alias': u'!lambda x: x[\'metric\'].split(\'.\')[-1] + " in MBs"', u'paneIndex': 0, u'yTransform': u'lambda x: x/1024', u'query': {u'aggregator': u'sum', u'metric': u'proc.meminfo.buffers', u'rate': False, u'tags': {}}}, {u'status': u'querying', u'alias': u'!lambda x: x[\'metric\'].split(\'.\')[-1] + " in MBs"', u'paneIndex': 0, u'yTransform': u'lambda x: x/1024', u'query': {u'aggregator': u'sum', u'metric': u'proc.meminfo.cached', u'rate': False, u'tags': {}}}, {u'status': u'querying', u'yTransform': u'lambda x: x/1024', u'paneIndex': 0, u'alias': u'!lambda x: x[\'metric\'].split(\'.\')[-1] + " in MBs"', u'query': {u'aggregator': u'sum', u'metric': u'proc.meminfo.inactive', u'rate': False, u'tags': {}}, 'data': [{'dps': [(1427713433000, 126934619.25), (1427713442000, 122355170.39999992), (1427713448000, 116432330.39999999), (1427713457000, 112644835.1999999), (1427713463000, 112980062.39999999), (1427713472000, 113154607.19999999), (1427713478000, 113360730.40000001), (1427713487000, 114000023.1999999), (1427713493000, 114383992.8), (1427713502000, 113733972.0), (1427713508000, 112798360.80000001), (1427713517000, 112296664.8), (1427713523000, 112426228.0), (1427713532000, 113220793.60000001), (1427713538000, 113856816.0), (1427713547000, 114319903.19999991), (1427713553000, 114422127.19999999), (1427713562000, 114273077.59999999), 

......(a lot of data)


 (1427716956000, 92935858.400000006), (1427716962000, 93090792.799999997), (1427716971000, 94724960.0), (1427716977000, 95740433.599999994), (1427716986000, 95958864.799999997), (1427716992000, 96209615.200000003), (1427717001000, 96870844.0), (1427717007000, 97215199.199999988), (1427717016000, 97450089.599999994), (1427717022000, 62247596.0)], 'uuid': u'proc.meminfo.inactive{}', u'tags': {}, u'metric': u'proc.meminfo.inactive', u'aggregateTags': [u'host'], 'alias': u'inactive in MBs'}], 'uuid': 'sum:proc.meminfo.inactive{}'}]
2015-03-30 20:03:52,228 [ERROR metrilyx.dataserver.protocols 175] [Failure instance: Traceback: <type 'exceptions.OverflowError'>: Maximum recursion level reached
/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py:578:_runCallbacks
/usr/local/lib/python2.7/dist-packages/metrilyx/httpclients/__init__.py:368:__partialResponseCallback
/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py:383:callback
/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py:491:_startRunCallbacks
--- <exception caught here> ---
/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py:578:_runCallbacks
/usr/local/lib/python2.7/dist-packages/metrilyx/dataserver/protocols.py:169:partialResponseCallback
]

thx~

**Comment by euforia** [comment]
Looks like the app is working now.  It's a question of your dashboard config.  

The orange exclamation marks on the dashboard should tell you whats going on.  There's probably a  bad transform somewhere in the dashboard.  That particular dashboard is a sample and may not contain metrics in your environment.  This will all depend on your dataset.

Play around with the adhoc graphs with your particular metrics or create a new dashboard and this error shouldn't pop up again.

**Comment by euforia** [comment]
Also which version are you running?

**Comment by godfreyhe** [comment]
metrilyx-2.0_2.5.0-12_amd64.deb

**Comment by euforia** [comment]
Sorry missed that in your earlier post.  That deb was made and tested on ubuntu 14.04.  Let me see if i can do some testing on 12.04.   In the meantime you can either do a manual install or try on 14.04.

**Comment by euforia** [comment]
I've confirmed that package will not work with ubuntu 12.04.  Different libraries between 12 and 14.  I'll post up another one and remove the current one in the mean time.

**Comment by euforia** [comment]
I've updated the packages and can be found here - https://github.com/Ticketmaster/metrilyx-2.0/releases

There's one there explicitly for ubuntu12.04.  

Apologies for the confusion.  I'll keep this open until you have it resolved.

**Comment by godfreyhe** [comment]
thank you very much

**Comment by godfreyhe** [comment]
I can install the lastest version app (metrilyx-2.0_2.5.1-5_amd64.deb) much easlier. However I can't get any graphs, there are some errors at /opt/metrilyx/log/metrilyx-modelmanager.log:
spawned uWSGI worker 19 (pid: 8725, cores: 1)
spawned uWSGI worker 20 (pid: 8726, cores: 1)
Error opening file for reading: Permission denied
[pid: 8726|app: 0|req: 1/1] 127.0.0.1 () {38 vars in 633 bytes} [Wed Apr  1 08:46:37 2015] GET /api/config => generated 420 bytes in 142 msecs (HTTP/1.1 200) 3 headers in 92 bytes (1 switches on core 0)
[pid: 8726|app: 0|req: 2/2] 127.0.0.1 () {38 vars in 639 bytes} [Wed Apr  1 08:46:38 2015] GET /api/graphmaps => generated 160 bytes in 9 msecs (HTTP/1.1 200) 3 headers in 98 bytes (2 switches on core 0)
[pid: 8726|app: 0|req: 3/3] 127.0.0.1 () {38 vars in 643 bytes} [Wed Apr  1 08:46:38 2015] GET /api/schemas/pod => generated 53 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 92 bytes (2 switches on core 0)
[pid: 8726|app: 0|req: 4/4] 127.0.0.1 () {38 vars in 658 bytes} [Wed Apr  1 08:46:38 2015] GET /api/graphmaps/Overview? => generated 7957 bytes in 5 msecs (HTTP/1.1 200) 3 headers in 112 bytes (2 switches on core 0)

**Comment by clohtd** [comment]
"Error opening file for reading: Permission denied"

**Comment by euforia** [comment]
As clohtd mentioned.  One of the files permissions are off.  I'm betting it's /opt/metrilyx/run/metrilyx...sock

Can you send me the output of ls -l /opt/metrilyx/run and also the version of nginx you are using?

Also join the irc channel.  Things will go much faster.

**Comment by euforia** [comment]
I've uploaded a new package with some more fixes but may solve your permissions issue.  Give it go and let me know.  Ive tested the new package (metrilyx-2.0_2.5.1-6_amd64.deb) and am not seeing any apparent errors.

**Comment by euforia** [comment]
Ran a final test on a vagrant ubuntu/precise64 flavor with the above latest 2.5.1 package and it checks out.  Let me know if you still have issues with it.
