### ISSUE TITLE
data server start failed

### ISSUE THREAD

**Issue by louzhenyu** [Ticketmaster/metrilyx-2.0#75]
Dear all,

/etc/init.d/metrilyx status
metrilyx-cacher running... 2061
metrilyx-dataserver not running
metrilyx-modelmanager running... 2109 2119 2120 2121 2122 2123 2124 2125 2126 2127 2128 2129 2130 2131 2132 2133 2134 2135 2136 2137 2138
----------------------------------------------------------------------------

Traceback (most recent call last):
  File "/opt/metrilyx/bin/metrilyx-dataserver.py", line 13, in <module>
    from twisted.internet import reactor
  File "/opt/metrilyx/usr/lib64/python2.6/site-packages/twisted/__init__.py", line 56, in <module>
    from twisted.python import compat
ImportError: No module named python
----------------------------------------------------------------------------
[root@master metrilyx]# python --version
Python 2.6.6
----------------------------------------------------------------------------

what suggestion?

**Comment by louzhenyu** [comment]
I do as below and dataserver start successfully:
[root@master bin]# vim set-run-env.sh

#! /bin/bash

#
# source /opt/metrilyx/bin/set-run-env.sh
#

METRILYX_HOME="/opt/metrilyx"

export PYTHONPATH=$METRILYX_HOME/usr/lib/python2.6/site-packages:$METRILYX_HOME/usr/lib64/python2.6/site-packages

changed to:
#! /bin/bash

#
# source /opt/metrilyx/bin/set-run-env.sh
#

METRILYX_HOME="/opt/metrilyx"

export PYTHONPATH=$METRILYX_HOME/usr/lib/python2.6/site-packages:$METRILYX_HOME/usr/lib64/python2.6/site-packages:/usr/bin

/usr/bin is where python located.

**Comment by louzhenyu** [comment]
but when I access website, get these errors:
 GET http://192.168.5.126/api/config 502 (Bad Gateway)
app.js:32 Object {data: "<html>
↵<head><title>502 Bad Gateway</title></head…disable MSIE and Chrome friendly error page -->
↵", status: 502, headers: function, config: Object}
angular.js:9419 Error: [$injector:unpr] http://errors.angularjs.org/1.2.9/$injector/unpr?p0=ConfigurationProvider%20%3C-%20Configuration%20%3C-%20Metrics%20%3C-%20metricSearchPanelDirective
    at Error (native)
    at http://192.168.5.126/libs/angular/1.2.9/angular.min.js:6:449
    at http://192.168.5.126/libs/angular/1.2.9/angular.min.js:32:125
    at Object.c [as get] (http://192.168.5.126/libs/angular/1.2.9/angular.min.js:30:200)
    at http://192.168.5.126/libs/angular/1.2.9/angular.min.js:32:193
    at c (http://192.168.5.126/libs/angular/1.2.9/angular.min.js:30:200)
    at Object.d [as invoke] (http://192.168.5.126/libs/angular/1.2.9/angular.min.js:30:417)
    at http://192.168.5.126/libs/angular/1.2.9/angular.min.js:32:211
    at c (http://192.168.5.126/libs/angular/1.2.9/angular.min.js:30:200)
    at Object.d [as invoke] (http://192.168.5.126/libs/angular/1.2.9/angular.min.js:30:417)
angular.js:7997 GET http://192.168.5.126/api/graphmaps 502 (Bad Gateway)
angular.js:9419 Error: [$injector:unpr] http://errors.angularjs.org/1.2.9/$injector/unpr?p0=ConfigurationProvider%2…uration%20%3C-%20WsHighstockGraphHelper%20%3C-%20wsHighstockGraphDirective
    at Error (native)
    at http://192.168.5.126/libs/angular/1.2.9/angular.min.js:6:449
    at http://192.168.5.126/libs/angular/1.2.9/angular.min.js:32:125
    at Object.c [as get] (http://192.168.5.126/libs/angular/1.2.9/angular.min.js:30:200)
    at http://192.168.5.126/libs/angular/1.2.9/angular.min.js:32:193
    at c (http://192.168.5.126/libs/angular/1.2.9/angular.min.js:30:200)
    at Object.d [as invoke] (http://192.168.5.126/libs/angular/1.2.9/angular.min.js:30:417)
    at http://192.168.5.126/libs/angular/1.2.9/angular.min.js:32:211
    at c (http://192.168.5.126/libs/angular/1.2.9/angular.min.js:30:200)
    at Object.d [as invoke] (http://192.168.5.126/libs/angular/1.2.9/angular.min.js:30:417)
angular.js:9419 Error: [$injector:unpr] http://errors.angularjs.org/1.2.9/$injector/unpr?p0=ConfigurationProvider%20%3C-%20Configuration
    at Error (native)
    at http://192.168.5.126/libs/angular/1.2.9/angular.min.js:6:449
    at http://192.168.5.126/libs/angular/1.2.9/angular.min.js:32:125
    at Object.c [as get] (http://192.168.5.126/libs/angular/1.2.9/angular.min.js:30:200)
    at http://192.168.5.126/libs/angular/1.2.9/angular.min.js:32:193
    at c (http://192.168.5.126/libs/angular/1.2.9/angular.min.js:30:200)
    at d (http://192.168.5.126/libs/angular/1.2.9/angular.min.js:30:417)
    at Object.instantiate (http://192.168.5.126/libs/angular/1.2.9/angular.min.js:31:80)
    at http://192.168.5.126/libs/angular/1.2.9/angular.min.js:61:486
    at link (http://192.168.5.126/libs/angular/1.2.9/angular-route.min.js:7:208) <div ng-view="" class="ng-scope">

**Comment by euforia** [comment]
Your setup doesn't look like a standard one, since these are environment setup errors.  

I would recommend you start with a fresh system.

Install epel and rpmforge repos

do a yum update

install the metrilyx rpm.

If you need more help you can also join the irc channel chat.freenode.net#metrilyx

**Comment by louzhenyu** [comment]
Dear euforia,
     I've set up a fresh system, and met below error:
/etc/init.d/nginx start
Starting nginx: nginx: [emerg] unknown directive "least_conn" in /etc/nginx/conf.d/metrilyx.conf:8
                                                           [FAILED]

**Comment by euforia** [comment]
Just missed you again on irc.

You can either comment that line out or install a newer version > 1.4 of nginx.

**Comment by louzhenyu** [comment]
:) https://github.com/Ticketmaster/metrilyx-2.0/releases/download/v2.5.0/metrilyx-2.0-2.5.0-10.el6.x86_64.rpm

**Comment by louzhenyu** [comment]
Dear euforia,
         I use the fresh system, view the website and get the same error:
http://192.168.5.127/api/config Failed to load resource: the server responded with a status of 502 (Bad Gateway)
app.js:32 Object
angular.min.js:84 Error: [$injector:unpr] http://errors.angularjs.org/1.2.9/$injector/unpr?p0=ConfigurationProvider%20%3C-%20Configuration%20%3C-%20Metrics%20%3C-%20metricSearchPanelDirective
    at Error (native)
    at http://192.168.5.127/libs/angular/1.2.9/angular.min.js:6:449
    at http://192.168.5.127/libs/angular/1.2.9/angular.min.js:32:125
    at Object.c [as get] (http://192.168.5.127/libs/angular/1.2.9/angular.min.js:30:200)
    at http://192.168.5.127/libs/angular/1.2.9/angular.min.js:32:193
    at c (http://192.168.5.127/libs/angular/1.2.9/angular.min.js:30:200)
    at Object.d [as invoke] (http://192.168.5.127/libs/angular/1.2.9/angular.min.js:30:417)
    at http://192.168.5.127/libs/angular/1.2.9/angular.min.js:32:211
    at c (http://192.168.5.127/libs/angular/1.2.9/angular.min.js:30:200)
    at Object.d [as invoke] (http://192.168.5.127/libs/angular/1.2.9/angular.min.js:30:417)
http://192.168.5.127/api/graphmaps Failed to load resource: the server responded with a status of 502 (Bad Gateway)
angular.min.js:84 Error: [$injector:unpr] http://errors.angularjs.org/1.2.9/$injector/unpr?p0=ConfigurationProvider%2…uration%20%3C-%20WsHighstockGraphHelper%20%3C-%20wsHighstockGraphDirective
    at Error (native)

**Comment by louzhenyu** [comment]
I have no idea on how to solve this:
angular.js:7997 GET http://192.168.5.127/api/config 502 (Bad Gateway)
app.js:32 Object {data: "<html>
↵<head><title>502 Bad Gateway</title></head…disable MSIE and Chrome friendly error page -->
↵", status: 502, headers: function, config: Object}
angular.js:9419 Error: [$injector:unpr] http://errors.angularjs.org/1.2.9/$injector/unpr?p0=ConfigurationProvider%20%3C-%20Configuration%20%3C-%20Metrics%20%3C-%20metricSearchPanelDirective
    at Error (native)
    at http://192.168.5.127/libs/angular/1.2.9/angular.min.js:6:449
    at http://192.168.5.127/libs/angular/1.2.9/angular.min.js:32:125
    at Object.c [as get] (http://192.168.5.127/libs/angular/1.2.9/angular.min.js:30:200)
    at http://192.168.5.127/libs/angular/1.2.9/angular.min.js:32:193
    at c (http://192.168.5.127/libs/angular/1.2.9/angular.min.js:30:200)
    at Object.d [as invoke] (http://192.168.5.127/libs/angular/1.2.9/angular.min.js:30:417)
    at http://192.168.5.127/libs/angular/1.2.9/angular.min.js:32:211

**Comment by louzhenyu** [comment]
I've followed your suggestion to install nginx1.6.2, and change parameter user from nginx to root in nginx.conf,but the website not work yet.

**Comment by euforia** [comment]
i need the logs from /opt/metrilyx/log/*.  The browser logs are not helpful at this point.

**Comment by louzhenyu** [comment]
[root@masterlou log]# vim metrilyx-modelmanager.log
your mercy for graceful operations on workers is 60 seconds
mapped 1527792 bytes (1491 KB) for 20 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xc0b870 pid: 3002 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 3002)
spawned uWSGI worker 1 (pid: 3012, cores: 1)
spawned uWSGI worker 2 (pid: 3013, cores: 1)
spawned uWSGI worker 3 (pid: 3014, cores: 1)
spawned uWSGI worker 4 (pid: 3015, cores: 1)
spawned uWSGI worker 5 (pid: 3016, cores: 1)
spawned uWSGI worker 6 (pid: 3017, cores: 1)
spawned uWSGI worker 7 (pid: 3018, cores: 1)
spawned uWSGI worker 8 (pid: 3019, cores: 1)
spawned uWSGI worker 9 (pid: 3020, cores: 1)
spawned uWSGI worker 10 (pid: 3021, cores: 1)
spawned uWSGI worker 11 (pid: 3022, cores: 1)
spawned uWSGI worker 12 (pid: 3023, cores: 1)
spawned uWSGI worker 13 (pid: 3024, cores: 1)
spawned uWSGI worker 14 (pid: 3025, cores: 1)
spawned uWSGI worker 15 (pid: 3026, cores: 1)
spawned uWSGI worker 16 (pid: 3027, cores: 1)
spawned uWSGI worker 17 (pid: 3028, cores: 1)
spawned uWSGI worker 18 (pid: 3029, cores: 1)
spawned uWSGI worker 19 (pid: 3030, cores: 1)
spawned uWSGI worker 20 (pid: 3031, cores: 1)

**Comment by louzhenyu** [comment]
missed some info in the front of log:
your processes number limit is 7732
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /opt/metrilyx/run/modelmanager.sock fd 3
Python version: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xc0b870
your server socket listen backlog is limited to 100 connections

**Comment by louzhenyu** [comment]
Please help!

**Comment by euforia** [comment]
You have not provided me with the needed info.  The above logs do not provide any information.  Please check if the nginx error logs have anything and send those to me.

**Comment by louzhenyu** [comment]
error log from nginx:
2015/04/03 22:54:24 [crit] 1453#0: *3 connect() to unix:///opt/metrilyx/run/modelmanager.sock failed (13: Permission denied) while connecting to upstream, client: 192.168.5.243, server: , request: "GET /api/config HTTP/1.1", upstream: "uwsgi://unix:///opt/metrilyx/run/modelmanager.sock:", host: "192.168.5.127", referrer: "http://192.168.5.127/"
2015/04/03 22:54:25 [error] 1453#0: *7 open() "/opt/metrilyx/www/favicon.ico" failed (2: No such file or directory), client: 192.168.5.243, server: , request: "GET /favicon.ico HTTP/1.1", host: "192.168.5.127"
2015/04/03 22:54:25 [crit] 1453#0: *3 connect() to unix:///opt/metrilyx/run/modelmanager.sock failed (13: Permission denied) while connecting to upstream, client: 192.168.5.243, server: , request: "GET /api/graphmaps HTTP/1.1", upstream: "uwsgi://unix:///opt/metrilyx/run/modelmanager.sock:", host: "192.168.5.127", referrer: "http://192.168.5.127/"

**Comment by louzhenyu** [comment]
i first try to fix nginx 13: Permission denied. thanks.

**Comment by euforia** [comment]
yes thats the issue - make sure that file is owned by the user nginx is running as.

**Comment by louzhenyu** [comment]
still failed after I changed owner of /opt/metrilyx/run/modelmanager.sock to root or nginx.

**Comment by louzhenyu** [comment]
vim /etc/selinux/config
SELINUX=disabled

now nginx 13: Permission denied fixed.

**Comment by louzhenyu** [comment]
WebSocket connection to 'ws://masterlou/api/data?compressed=true' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED

any suggestion?

**Comment by louzhenyu** [comment]
I colse this issue and create a new one.

**Comment by euforia** [comment]
in the configuration file under the websocket section add a field called hostname and set it to the ip address.
