### ISSUE TITLE
Only see grab & drop box

### ISSUE THREAD

**Issue by djcrumple** [Ticketmaster/metrilyx-2.0#80]
Just installed v2.5.1 from package on a fresh ubuntu 14.04 VM. When I go to http://metrilyx_ip, it redirects to http://metrilyx_ip/#/graph, and the entire screen is a single white box with "Drag metrics here from search". No other controls are on the screen.

**Comment by djcrumple** [comment]
Here's what I see in the chrome dev console

GET http://10.10.123.100/api/config 500 (Internal Server Error)
app.js:32 Object {data: "Internal Server Error", status: 500, headers: function, config: Object}
angular.js:9419

Error: [$injector:unpr] http://errors.angularjs.org/1.2.9/$injector/unpr?p0=ConfigurationProvider%20%3C-%20Configuration%20%3C-%20Metrics%20%3C-%20metricSearchPanelDirective
    at Error (native)
    at http://10.10.123.100/libs/angular/1.2.9/angular.min.js:6:449
    at http://10.10.123.100/libs/angular/1.2.9/angular.min.js:32:125
    at Object.c [as get] (http://10.10.123.100/libs/angular/1.2.9/angular.min.js:30:200)
    at http://10.10.123.100/libs/angular/1.2.9/angular.min.js:32:193
    at c (http://10.10.123.100/libs/angular/1.2.9/angular.min.js:30:200)
    at Object.d [as invoke] (http://10.10.123.100/libs/angular/1.2.9/angular.min.js:30:417)
    at http://10.10.123.100/libs/angular/1.2.9/angular.min.js:32:211
    at c (http://10.10.123.100/libs/angular/1.2.9/angular.min.js:30:200)
    at Object.d [as invoke] (http://10.10.123.100/libs/angular/1.2.9/angular.min.js:30:417)
angular.js:9419 

Error: [$injector:unpr] http://errors.angularjs.org/1.2.9/$injector/unpr?p0=ConfigurationProvider%2…uration%20%3C-%20WsHighstockGraphHelper%20%3C-%20wsHighstockGraphDirective
    at Error (native)
    at http://10.10.123.100/libs/angular/1.2.9/angular.min.js:6:449
    at http://10.10.123.100/libs/angular/1.2.9/angular.min.js:32:125
    at Object.c [as get] (http://10.10.123.100/libs/angular/1.2.9/angular.min.js:30:200)
    at http://10.10.123.100/libs/angular/1.2.9/angular.min.js:32:193
    at c (http://10.10.123.100/libs/angular/1.2.9/angular.min.js:30:200)
    at Object.d [as invoke] (http://10.10.123.100/libs/angular/1.2.9/angular.min.js:30:417)
    at http://10.10.123.100/libs/angular/1.2.9/angular.min.js:32:211
    at c (http://10.10.123.100/libs/angular/1.2.9/angular.min.js:30:200)
    at Object.d [as invoke] (http://10.10.123.100/libs/angular/1.2.9/angular.min.js:30:417)
angular.js:9419 

Error: [$injector:unpr] http://errors.angularjs.org/1.2.9/$injector/unpr?p0=ConfigurationProvider%20%3C-%20Configuration
    at Error (native)
    at http://10.10.123.100/libs/angular/1.2.9/angular.min.js:6:449
    at http://10.10.123.100/libs/angular/1.2.9/angular.min.js:32:125
    at Object.c [as get] (http://10.10.123.100/libs/angular/1.2.9/angular.min.js:30:200)
    at http://10.10.123.100/libs/angular/1.2.9/angular.min.js:32:193
    at c (http://10.10.123.100/libs/angular/1.2.9/angular.min.js:30:200)
    at d (http://10.10.123.100/libs/angular/1.2.9/angular.min.js:30:417)
    at Object.instantiate (http://10.10.123.100/libs/angular/1.2.9/angular.min.js:31:80)
    at $get (http://10.10.123.100/libs/angular/1.2.9/angular.min.js:61:486)
    at link (http://10.10.123.100/libs/angular/1.2.9/angular-route.min.js:7:208) <div ng-view="" class="ng-scope">
angular.js:7997 

GET http://10.10.123.100/api/graphmaps 500 (Internal Server Error)

**Comment by euforia** [comment]
Can you send me errors from the nginx error log as well as the metrilyx-modelmanager.log?

Metrilyx logs can be found under /opt/metrilyx/log

**Comment by djcrumple** [comment]
/var/log/nginx/error.log is empty

/opt/metrilyx/log/metrilyx-modelmanager.log

--- no python application found, check your startup logs for errors ---
[pid: 7988|app: -1|req: -1/1] 10.10.123.218 () {42 vars in 710 bytes} [Fri Apr  3 09:04:04 2015] GET /api/config => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7984|app: -1|req: -1/2] 10.10.123.218 () {40 vars in 685 bytes} [Fri Apr  3 09:04:04 2015] GET /api/graphmaps => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7973|app: -1|req: -1/3] 10.10.123.218 () {40 vars in 679 bytes} [Fri Apr  3 09:04:15 2015] GET /api/config => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7985|app: -1|req: -1/4] 10.10.123.218 () {40 vars in 685 bytes} [Fri Apr  3 09:04:15 2015] GET /api/graphmaps => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7988|app: -1|req: -1/5] 10.10.123.218 () {38 vars in 673 bytes} [Fri Apr  3 09:25:46 2015] GET /admin => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7969|app: -1|req: -1/6] 10.10.123.218 () {40 vars in 682 bytes} [Fri Apr  3 09:25:50 2015] GET /api/config => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7979|app: -1|req: -1/7] 10.10.123.218 () {40 vars in 688 bytes} [Fri Apr  3 09:25:50 2015] GET /api/graphmaps => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7985|app: -1|req: -1/8] 10.10.123.218 () {40 vars in 689 bytes} [Fri Apr  3 09:25:59 2015] GET /api/config => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7978|app: -1|req: -1/9] 10.10.123.218 () {40 vars in 695 bytes} [Fri Apr  3 09:25:59 2015] GET /api/graphmaps => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7988|app: -1|req: -1/10] 10.10.123.218 () {40 vars in 679 bytes} [Fri Apr  3 09:26:33 2015] GET /api/config => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7979|app: -1|req: -1/11] 10.10.123.218 () {40 vars in 685 bytes} [Fri Apr  3 09:26:33 2015] GET /api/graphmaps => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7988|app: -1|req: -1/12] 10.10.123.218 () {40 vars in 679 bytes} [Fri Apr  3 09:34:41 2015] GET /api/config => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7979|app: -1|req: -1/13] 10.10.123.218 () {40 vars in 685 bytes} [Fri Apr  3 09:34:41 2015] GET /api/graphmaps => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7988|app: -1|req: -1/14] 10.10.123.218 () {42 vars in 710 bytes} [Fri Apr  3 09:35:17 2015] GET /api/config => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7977|app: -1|req: -1/15] 10.10.123.218 () {40 vars in 685 bytes} [Fri Apr  3 09:35:17 2015] GET /api/graphmaps => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)

**Comment by djcrumple** [comment]
Hmm... I stopped and started metrilyx again and the problem went away.

**Comment by euforia** [comment]
This does not look good - "--- no python application found, check your startup logs for errors ---".  Not sure if that's causing issues.  Everything working ok?

**Comment by djcrumple** [comment]
It is working now. I'm able to search for metrics and draw graphs. Thanks!

**Comment by euforia** [comment]
Awesome.  I just found a bug in that release where the models can't be save.  Keep an eye out for a new package.
