### ISSUE TITLE
Can't save Dashboard

### ISSUE THREAD

**Issue by louzhenyu** [Ticketmaster/metrilyx-2.0#84]
Hi,
    After I created a new dashboard and clicked save menu button, it got an error: can't save readonly db?

**Comment by euforia** [comment]
check the permissions on the sqlite db.

**Comment by clohtd** [comment]
I just encountered this.  The fix for me was to change ownership of the db AND the data folder to the account that nginx runs under.
```bash
chown -R nginx:root /opt/metrilyx/data
```
also, just in case...
```bash
chmod 755 /opt/metrilyx/data
chmod 644 /opt/metrilyx/data/metrilyx.sqlite3
```

**Comment by louzhenyu** [comment]
thank you very much, can this be re-configed in rpm? i think it'll be better.

**Comment by euforia** [comment]
I'll let you know.  at this point i'm really just looking to create docker images. Closing this issue for now.
