### ISSUE TITLE
debian package has django 1.8 installed

### ISSUE THREAD

**Issue by abraithwaite** [Ticketmaster/metrilyx-2.0#86]
After installing the debian on jessie and trying to start the server, I was getting a deprecation error in the logs (sorry, I lost it in my scrollback).  But after digging in, I found that the debian package has django 1.8 installed when the requirements and docs say it should be 1.6.5.

```
abraithwaite at jessie in /tmp
$ dpkg-deb -R metrilyx-2.0_2.5.1-18_amd64.deb met

abraithwaite at jessie in /tmp
$ cat met/opt/metrilyx/usr/local/lib/python2.7/dist-packages/django/__init__.py | grep -i ver
from django.utils.version import get_version
VERSION = (1, 8, 0, 'final', 0)
__version__ = get_version(VERSION)

abraithwaite at jessie in /tmp
$ ls met/opt/metrilyx/usr/local/lib/python2.7/dist-packages/django*
django/                                django_cors_headers-0.12.egg-info/     djangorestframework-2.3.13.dist-info/
Django-1.6.5.dist-info/                django_filter-0.7.dist-info/           django_reversion-1.8.0.egg-info/
Django-1.8.dist-info/                  django_filters/
```

**Comment by euforia** [comment]
I suspect that's coming from django_reversion.  Does metrilyx actually run?  I wonder if it's only needed fore reversion.  Please let me know.

**Comment by abraithwaite** [comment]
It was a weird failure because django started, but every request was a 500 error.  Maybe if an app fails to load, django still tries to run.   Everything but django launched fine though.

Which version of django is actually required by the app though?  The docs and the requirements contradict the django version in the debian.

**Comment by euforia** [comment]
it should be 1.6.5.  There shouldn't be a reference to 1.8 anywhere. Not quite sure how it got there.  Anything above 1.6.5 does have breaking changes.  Is django 1.8 already installed on you system?

**Comment by euforia** [comment]
I'm usually available on irc: freenode#metrilyx  May get faster results.

**Comment by abraithwaite** [comment]
Nope.  If you download the debian and unpack the debian, you'll see that the packaged version is 1.8.  That's what I was trying to show in the initial report (sorry if it wasn't clear).

However, now the URL seems to be 404ing:

https://github.com/Ticketmaster/metrilyx-2.0/releases/download/v2.5.1/metrilyx-2.0_2.5.1-18_amd64.deb

**Comment by euforia** [comment]
I pushed up the version with a fix, which is why the download fails.  

It seems to be happening in the ubuntu package build.  I'll have to dig a bit deeper as I've only tested the .deb package on ubuntu 14.04.  

You man need to install the manual route until I have a fix or try on ubuntu 14.

**Comment by euforia** [comment]
Closing.  Feel free to open if necessary.
