### ISSUE TITLE
Metrilyx only functions in console that started the process

### ISSUE THREAD

**Issue by clohtd** [Ticketmaster/metrilyx-2.0#90]
Latest rpm release.
When I launch metrilyx using the init.d scripts, it seems to launch properly.
When I then pull up a dashboard, I see the dashboard rendering to my shell.console in real time.  It's throwing things such as:

````
 'start': 1430337005,
 'tags': {},
 'thresholds': {u'danger': {u'max': 10000000000000000L,
                            u'min': 10000000000000000L},
                u'info': {u'max': 99999999999999L, u'min': 99999999999999L},
                u'warning': {u'max': 999999999999999L,
                             u'min': 999999999999999L}}}
````

I find that whenever that stuff is spamming the console, the dashboards render properly within the Metrilyx web interface.

If I exit the console however, then Metrilyx stops rendering graphs.  I can log back in and see that the processes "seem" to be running.  Nothing will render, however, until I exit restart the service and allow the console to be spammed.

It seems like it needs a nohup somewhere.  I'm just trying to figure out what is throwing this.  So far I have modified the init.d's for cacher, modelmanager, and dataserver, adding a nohup to each, and I haven't been successful in stopping the console spam.

**Comment by euforia** [comment]
which console?  javascript or linux?

**Comment by clohtd** [comment]
The linux/bash console that I use to "service start metrilx"

**Comment by euforia** [comment]
I think the problem is in this line - https://github.com/Ticketmaster/metrilyx-2.0/blob/master/etc/init.d/metrilyx-dataserver#L32

Try changing that line to :

METRILYX_HOME=${APP_HOME} PYTHONPATH=${PYTHONPATH} ${BIN} ${OPTS} 2>&1 &

Let me know.

**Comment by clohtd** [comment]
That's the line, however the redirect wasn't enough for me.  I had to add a nohup before the ${BIN}

This works for me:  METRILYX_HOME=${APP_HOME} PYTHONPATH=${PYTHONPATH} nohup ${BIN} ${OPTS} 2>&1 &

**Comment by euforia** [comment]
k.  I'll test it out and update accordingly.

**Comment by harryfwong** [comment]
I was having the same issue and the 2nd fix above worked
