### ISSUE TITLE
Metrilyx dashboard not loading

### ISSUE THREAD

**Issue by RowZay** [Ticketmaster/metrilyx-2.0#96]
I've followed everything in Quick Start. I'm running Ubuntu 14.04 and the server seems to be running fine. I've also added the hostname to websocket, no luck.

**Comment by euforia** [comment]
Can you send me the javascript console output when you try to load a metric?

**Comment by RowZay** [comment]
There are no results when I try to search for a metric. The only thing I can do is select Overview and TSD from Dashboards. This just displays all the metrics with the loading gif.

**Comment by clohtd** [comment]
I ran in to that problem.  The metrilyx-cacher service wasn't caching the metrix.  I forget what I did to fix it; but had to ensure that the cacher was working.

**Comment by clohtd** [comment]
/opt/metrilyx/log/*.log will have answers.

**Comment by RowZay** [comment]
@clohtd What should I be looking for?

**Comment by euforia** [comment]
run the following: /etc/init.d/metrilyx status

Then you can issue: /etc/init.d/metrilyx-cacher start 

if you need to start it.

Also the javascript console in the browser will also have information.

**Comment by hugo021** [comment]
@RowZay Had you reslove that problem?I run into that problem too.

**Comment by euforia** [comment]
@hugo021 : is the metrilyx-cacher running?

**Comment by hugo021** [comment]
yes，the metrilyx-cache running，and it work，but no any data or graph return.

**Comment by euforia** [comment]
can you paste me the output of the javascript console on your browser as you're loading the page?

**Comment by hugo021** [comment]
解析 'overflow' 的值时出错。  声明被丢弃。 style.css:4:11
解析 'font' 的值时出错。  声明被丢弃。 style.css:119:7
解析 'font' 的值时出错。  声明被丢弃。 style.css:120:7
未知属性 'user-select'。  声明被丢弃。 style.css:270:14
解析 'background' 的值时出错。  声明被丢弃。 style.css:292:13
解析 'background' 的值时出错。  声明被丢弃。 style.css:321:13
解析 'background' 的值时出错。  声明被丢弃。 style.css:323:17
解析 'background' 的值时出错。  声明被丢弃。 style.css:324:18
解析 'background' 的值时出错。  声明被丢弃。 style.css:376:13
解析 'background' 的值时出错。  声明被丢弃。 style.css:378:17
解析 'background' 的值时出错。  声明被丢弃。 style.css:379:18
解析 'cursor' 的值时出错。  声明被丢弃。 style.css:534:9
解析 'overflow-x' 的值时出错。  声明被丢弃。 style.css:541:12
未知属性 'text-wrap'。  声明被丢弃。 style.css:597:10
解析 'cursor' 的值时出错。  声明被丢弃。 style.css:621:9
解析 'cursor' 的值时出错。  声明被丢弃。 style.css:624:9
解析 'cursor' 的值时出错。  声明被丢弃。 style.css:625:9
未知属性 'text-wrap'。  声明被丢弃。 style.css:643:10
未知伪类或者伪元素 '-webkit-input-placeholder'。  选择器错误导致忽略规则集。 style.css:944:25
未知伪类或者伪元素 '-webkit-input-placeholder'。  选择器错误导致忽略规则集。 style.css:952:28
未知伪类或者伪元素 '-webkit-input-placeholder'。  选择器错误导致忽略规则集。 style.css:955:38
未知属性 '-moz-filter'。  声明被丢弃。 style.css:1310:13
解析 'word-wrap' 的值时出错。  声明被丢弃。 style.css:1390:12
未知伪类或者伪元素 '-webkit-search-cancel-button'。  选择器错误导致忽略规则集。 bootstrap.min.css:7:1619
预期为颜色，但却得到 'auto'。  预期为颜色，但却得到 '-webkit-focus-ring-color'。  预期为变量结尾，但却得到 '-webkit-focus-ring-color'。  解析 'outline' 的值时出错。  声明被丢弃。 bootstrap.min.css:7:3244
预期为变量结尾，但却得到 '\9 '。  解析 'margin-top' 的值时出错。  声明被丢弃。 bootstrap.min.css:7:21589
预期为颜色，但却得到 'auto'。  预期为颜色，但却得到 '-webkit-focus-ring-color'。  预期为变量结尾，但却得到 '-webkit-focus-ring-color'。  解析 'outline' 的值时出错。  声明被丢弃。 bootstrap.min.css:7:21871
未知伪类或者伪元素 '-webkit-outer-spin-button'。  选择器错误导致忽略规则集。 bootstrap.min.css:7:21943
未知伪类或者伪元素 '-ms-input-placeholder'。  选择器错误导致忽略规则集。 bootstrap.min.css:7:22924
未知伪类或者伪元素 '-webkit-input-placeholder'。  选择器错误导致忽略规则集。 bootstrap.min.css:7:22972
未知属性 'user-select'。  声明被丢弃。 bootstrap.min.css:7:27941
预期为颜色，但却得到 'auto'。  预期为颜色，但却得到 '-webkit-focus-ring-color'。  预期为变量结尾，但却得到 '-webkit-focus-ring-color'。  解析 'outline' 的值时出错。  声明被丢弃。 bootstrap.min.css:7:27990
预期为 'none'、网址或过滤功能，但却得到 'alpha('。  解析 'filter' 的值时出错。  声明被丢弃。 bootstrap.min.css:7:28359
未知属性 '-moz-osx-font-smoothing'。  声明被丢弃。 bootstrap.min.css:7:35589
预期为 'none'、网址或过滤功能，但却得到 'progid'。  解析 'filter' 的值时出错。  声明被丢弃。 bootstrap.min.css:7:45713
解析 'background-image' 的值时出错。  声明被丢弃。 bootstrap.min.css:7:72655
解析 'background-image' 的值时出错。  声明被丢弃。 bootstrap.min.css:7:73277
解析 'background-image' 的值时出错。  声明被丢弃。 bootstrap.min.css:7:73728
解析 'background-image' 的值时出错。  声明被丢弃。 bootstrap.min.css:7:74185
解析 'background-image' 的值时出错。  声明被丢弃。 bootstrap.min.css:7:74640
未知属性 'zoom'。  声明被丢弃。 bootstrap.min.css:7:75032
预期为 'none'、网址或过滤功能，但却得到 'alpha('。  解析 'filter' 的值时出错。  声明被丢弃。 bootstrap.min.css:7:82616
预期为 'none'、网址或过滤功能，但却得到 'alpha('。  解析 'filter' 的值时出错。  声明被丢弃。 bootstrap.min.css:7:82725
预期为 'none'、网址或过滤功能，但却得到 'alpha('。  解析 'filter' 的值时出错。  声明被丢弃。 bootstrap.min.css:7:83826
预期为 'none'、网址或过滤功能，但却得到 'alpha('。  解析 'filter' 的值时出错。  声明被丢弃。 bootstrap.min.css:7:83880
预期为 'none'、网址或过滤功能，但却得到 'alpha('。  解析 'filter' 的值时出错。  声明被丢弃。 bootstrap.min.css:7:84843
预期为 'none'、网址或过滤功能，但却得到 'alpha('。  解析 'filter' 的值时出错。  声明被丢弃。 bootstrap.min.css:7:84909
预期为 'none'、网址或过滤功能，但却得到 'alpha('。  解析 'filter' 的值时出错。  声明被丢弃。 bootstrap.min.css:7:88937
解析 'background-image' 的值时出错。  声明被丢弃。 bootstrap.min.css:7:88995
预期为 'none'、网址或过滤功能，但却得到 'progid'。  解析 'filter' 的值时出错。  声明被丢弃。 bootstrap.min.css:7:89210
解析 'background-image' 的值时出错。  声明被丢弃。 bootstrap.min.css:7:89378
预期为 'none'、网址或过滤功能，但却得到 'progid'。  解析 'filter' 的值时出错。  声明被丢弃。 bootstrap.min.css:7:89593
预期为 'none'、网址或过滤功能，但却得到 'alpha('。  解析 'filter' 的值时出错。  声明被丢弃。 bootstrap.min.css:7:89810
预期为变量结尾，但却得到 '\9 '。  解析 'background-color' 的值时出错。  声明被丢弃。 bootstrap.min.css:7:90710
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery-1.10.2.min.js:1:0
所用的 getPreventDefault() 已不赞成使用。请使用 defaultPrevented 替代。 jquery-1.10.2.min.js:5:0
"Adhoc Controller" Adhoc.js:149:8
"Annotations disabled!" Annotations.js:257:20
"edit-mode" Adhoc.js:123:20
"set" "edit-mode" angular-factories.js:225:12
预期为颜色，但却得到 '{'。  解析 'color' 的值时出错。  声明被丢弃。 10.210.241.36
预期为颜色，但却得到 ';'。  解析 'color' 的值时出错。  声明被丢弃。 10.210.241.36
解析 'display' 的值时出错。  声明被丢弃。 10.210.241.36
"Connected (metrilyx): Extensions: [permessage-deflate]" angular-factories.js:503:12
"Submitting queued requests:" 0 angular-factories.js:504:12
"Disconnected (metrilyx): clean=false, code=1006, reason=''" angular-factories.js:512:0

**Comment by hugo021** [comment]
@euforia can you tell me how the cache-server works,how does it get the mertics from opneTSB and where do they stored,thank you very much!

**Comment by euforia** [comment]
For starters your you're websocket is not connected.  

- Run /etc/init.d/metrilyx status and make sure all metrilyx services are running
- Make sure nginx is running
- check the logs under /opt/metrilyx/logs for additional info.

The cacher code can be found here: https://github.com/metrilyx/metrilyx-cacher

**Comment by hugo021** [comment]
@euforia 
def getQuery(self, request):
		'''
			Returns: A tuple with (url, method, request_body).  Body can be None 
			if method is 'GET' and the query is url encoded.
		'''
		try:
			baseUrl = "%s:%d%s?start=%s" %(self.uri, self.port,
							self.query_endpoint, request['start'])
		except Exception,e:
			print e, request
			raise RuntimeError(e)

		if request.has_key('end'):
			baseUrl += "&end=%d" %(request['end'])
		for s in request['series']:
			if s['query'].get('rate'):
				query = "&m=%(aggregator)s:rate:%(metric)s" %(s['query'])
			else:
				query = "&m=%(aggregator)s:%(metric)s" %(s['query'])
			tagstr = ",".join([ "%s=%s"%(k,v) for k,v in s['query']['tags'].items() ])
			if tagstr != "":
				baseUrl += query + "{" + tagstr + "}"
			else:
				baseUrl += query
		# uri, method, body
		return (str(baseUrl), 'GET', None)

how to test the function? I do not know what should i do to use getQuery()?can you give a example?thank you very much!

**Comment by euforia** [comment]
it would be an object/dict containing those fields/attributes.  What is it that you are trying to achieve so I have a better context?

**Comment by euforia** [comment]
Feel free to open if needed.  Closing
