### ISSUE TITLE
Issue changing timezone

### ISSUE THREAD

**Issue by ndcampbell** [Ticketmaster/metrilyx-2.0#98]
I am unable to change the timezone. I am running Metrilyx 2.5.1 and am trying to change to timezone to America/Chicago but all graphs seem to use UTC. Previous issues makes it look like I need to edit etc/settings.py but this does not exist in my installation. I did trying editing ./usr/lib/python2.6/site-packages/django/conf/project_template/project_name/settings.py but that did not seem to make any difference and I do not see any configs in my installation (rpm install) that allows me to change the timezone. Any ideas?

**Comment by euforia** [comment]
This is the one you are looking for - /usr/lib/python2.6/site-packages/metrilyx/settings.py

Let me know.

**Comment by ndcampbell** [comment]
Still did not really seem to work. I think it might just be an issue with our metrics though. Things collected from tcollector work just fine but manually inserted metrics seem stuck in UTC.

**Comment by euforia** [comment]
Everything stored in tsdb is epoch.  I'll close this for now.  Feel free to re-open if needed.
