### ISSUE TITLE
No graph/No data

### ISSUE THREAD

**Issue by eriklouise** [Ticketmaster/metrilyx-2.0#99]
Hello guys !

Platform Debian 7 x64, Python 2.7, OpenTSDB 2.1.1

I've got Metrilyx 2.5.1 almost working using the .deb package by manually installing the version 1.7.10 of Django (using this procedure: https://docs.djangoproject.com/en/1.8/topics/install/#removing-old-versions-of-django).

Now metrilyx is well displayed (with lateral search bar and so on). I can perform a search but when I drop a metric in the main view, nothing the loading gif appears then nothing happens.

The only warning I have in the metrilyx-modelmanager.log is :
/opt/metrilyx/usr/local/lib/python2.7/dist-packages/reversion/admin.py:129: RemovedInDjango18Warning: Options.module_name has been deprecated in favor of model_name
  info = opts.app_label, opts.module_name,

Note: my datas are working well in GnuPlot and Grafana.

Any suggestions ?

Best regards.
Erik

**Comment by euforia** [comment]
can you send me the javascript console log after you've dragged the metric onto the graph?

**Comment by eriklouise** [comment]
Actually the console in Chrome shows:
> Adhoc Controller
> Annotations disabled!
> edit-mode
> set edit-mode
> WebSocket connection to 'ws://xxxxx/api/data?compressed=true' failed: Error during WebSocket handshake: 'Connection' header value must contain 'Upgrade'
> Disconnected (metrilyx): clean=false, code=1006, reason=''
> Queueing event listener: f77598d6bbe1458d9ae05db775cfd451
> iConnect state: disconnected
> Re-connecting...
> WebSocket connection to 'ws://xxxxx/api/data?compressed=true' failed: Error during WebSocket handshake: 'Connection' header value must contain 'Upgrade'
> Disconnected (metrilyx): clean=false, code=1006, reason=''

And this is the partial content of my /etc/nginx/conf.d/metrilyx.conf

>    location /api/data {
>        proxy_pass http://dataprovider;
>        proxy_http_version 1.1;
>        proxy_set_header Upgrade $http_upgrade;
>        proxy_set_header Connection "upgrade";
>        proxy_buffering off;
>    }

I tryied to replace "upgrade" by "Upgrade" but the error keeps happening.

**Comment by euforia** [comment]
the websocket server seems to be the issue.  can you paste the /opt/metrilyx/log/metrilyx-dataserver.log? and the nginx/error.log as well?  that should have more info as to what is going on

**Comment by eriklouise** [comment]
Shame on me ! :-)

Actually I have an old version of nginx (1.2.1 which comes with Debian
Wheezy default repositories) and WebSockets are supported with nginx 1.3.13
and later.

*--*

*Erik LOUISE*
*Architecte Système d'Information Industriel*
Tel.: +33 (0) 4 76 62 43 00
Mob.: +33 (0) 6 07 90 50 22

*Thales Services S.A.S.*

Le Viséo

110, rue Blaise Pascal

38330 Montbonnot

www.thalesgroup.com

<http://www.thalesgroup.com/live>


2015-09-29 18:32 GMT+02:00 euforia <notifications@github.com>:
